# Generated by Django 4.2.7 on 2024-09-27 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='file_path',
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
