# Generated by Django 4.2.7 on 2024-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_template_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
