# Generated by Django 4.2.7 on 2024-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_template_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='project_name',
            field=models.TextField(),
        ),
    ]
